/**
 * Created by PhpStorm.
 * Author: DO HOANG ( shinkenger.vn9x@gmail.com )
 * Date: 9/30/2019
 * Time: 9:53 PM
 */

export enum AuthScope {
  CAN_ACCESS_ADMIN_PAGE = 1,
  CAN_SEE_DASHBOARD = 2,
  CAN_MANAGER_EMPLOYEES = 3,
  CAN_MANAGE_VEHICLE_CATEGORIES = 4,
  CAN_MANAGE_TICKETS = 5,
  CAN_MANAGE_VEHICLES = 6,
  CAN_MANAGE_CUSTOMERS = 7,
  CAN_MANAGE_CUSTOMER_TYPES = 8,
  CAN_MANAGE_SCHEDULES = 9,
  CAN_MANAGE_ORDERS = 10,
  CAN_MANAGE_POLICIES = 11,
  CAN_PUSH_NOTIFICATIONS = 12,
  CAN_MANAGE_LOCATION_LIBRARIES = 13,
  CAN_MANAGE_SCHEDULE_TEMPLATES = 14,
  CAN_MANAGE_VOYAGES = 15,
  CAN_SEE_USER_ACTION_HISTORIES = 16,
  CAN_EXPORTS_ORDERS_TO_EXCEL = 17,
  CAN_CREATE_BALANCE = 18,
  CAN_MANAGE_BALANCE = 19,
  CAN_MANAGE_MAINTENANCE_PLAN = 20,
  CAN_MANAGE_TRANSACTIONS = 21,
  CAN_MANAGE_REFUNDS = 22,
  CAN_DISPLAY_BALANCE = 23,
  CAN_CREATE_CUSTOMER_SCHEDULE_FOR_DAY = 24
}
