export const COLLAPSE_SIDEBAR = 'APP_COLLAPSE_SIDEBAR';
export const WINDOW_SIZE_CHANGE = 'APP_WINDOW_SIZE_CHANGE';
export const APP_USER_CHANGED = 'APP_USER_CHANGED';
export const FETCH_AUTH_DATA = 'FETCH_AUTH_DATA';
